### PR TITLE
feat: add support for CommitStats

### PR DESCRIPTION
**Pull request by olavloite**
Adds support for `CommitStats` to the JDBC driver.

### CODE REVIEW

**Review by thiagotnunes — APPROVED** [review]
LGTM

**Comment by skuruppu** [comment]
@olavloite I think we're almost ready to merge this. If you could please rebase and get it ready, that would be awesome.

**Comment by olavloite** [comment]
> @olavloite I think we're almost ready to merge this. If you could please rebase and get it ready, that would be awesome.

This should now be ready to go once Spanner client version 4.0.3 is released.

**Comment by skuruppu** [comment]
@olavloite Spanner Client version 5.0 is released 🎉

**Comment by olavloite** [comment]
> @olavloite Spanner Client version 5.0 is released

@skuruppu It seems that we should not (cannot?) release this until Spanner 5.0.0 is included in the google-cloud-libraries-bom. The linkage monitor checks that the most recent versions in the bom are compatible with each other, and the current version of the bom contains Spanner 4.0.1 which is not compatible with this change.

**Comment by skuruppu** [comment]
> @skuruppu It seems that we should not (cannot?) release this until Spanner 5.0.0 is included in the google-cloud-libraries-bom. The linkage monitor checks that the most recent versions in the bom are compatible with each other, and the current version of the bom contains Spanner 4.0.1 which is not compatible with this change.

Ah yikes ok, we'll have to request another BOM update then. @thiagotnunes would you be able to look into this?

**Pull request merged**
